#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import io
import json
import logging
import os
import string
import time
from pathlib import Path
from typing import Any

import numpy as np
from openai import OpenAI
from PIL import Image, ImageDraw, ImageFont

from annotators import _overlay_mask
from postprocess_annotations import slugify


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("verify")

DEFAULT_INPUT_DIR = Path("annotated_masks_full")
DEFAULT_SUMMARY_JSON = Path("postprocessed_annotations_summary_full.json")
# DEFAULT_OUTPUT_JSONL = Path("verified_annotations_glm8b_full.jsonl")
# DEFAULT_OUTPUT_JSONL = Path("verified_annotations_qw9b_full.jsonl")
DEFAULT_OUTPUT_JSONL = Path("verified_annotations_it8b_full.jsonl")
# DEFAULT_MODEL = "zai-org/GLM-4.6V-Flash"
# DEFAULT_MODEL = "Qwen/Qwen3.5-9B"
DEFAULT_MODEL = "OpenGVLab/InternVL3_5-8B"
DEFAULT_TOOLS = ("chefer", "attention", "grounded_sam", "sam3", "clipseg")

SYSTEM_PROMPT = (
    "You are an annotation verifier for visual rationale grounding. "
    "Be conservative and return valid JSON only."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Verify concept-level mask overlay proposals in annotated_masks "
            "using an OpenAI-compatible multimodal model."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Path to annotated_masks.",
    )
    parser.add_argument(
        "--summary-json",
        type=Path,
        default=DEFAULT_SUMMARY_JSON,
        help="Optional postprocessed_annotations_summary.json used to recover original concept names.",
    )
    parser.add_argument(
        "--output-jsonl",
        type=Path,
        default=DEFAULT_OUTPUT_JSONL,
        help="Incremental JSONL output path.",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help="Verifier model name.",
    )
    parser.add_argument(
        "--api-key",
        default="EMPTY",
        help="API key. Defaults to OPENAI_API_KEY.",
    )
    parser.add_argument(
        "--base-url",
        default='http://localhost:8080/v1',
        help="Optional OpenAI-compatible base URL. Defaults to OPENAI_BASE_URL.",
    )
    parser.add_argument(
        "--tools",
        nargs="+",
        default=list(DEFAULT_TOOLS),
        help="Preferred tool order to verify.",
    )
    parser.add_argument(
        "--min-candidates",
        type=int,
        default=2,
        help="Minimum number of candidate overlays required per concept.",
    )
    parser.add_argument(
        "--start-image",
        type=int,
        default=0,
        help="Start from this image index after sorting image IDs.",
    )
    parser.add_argument(
        "--limit-images",
        type=int,
        default=None,
        help="Process at most this many images.",
    )
    parser.add_argument(
        "--limit-concepts",
        type=int,
        default=None,
        help="Optional per-image concept limit.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing JSONL instead of resuming.",
    )
    parser.add_argument(
        "--save-composites-dir",
        type=Path,
        default='composites_mask_full',
        help="Optional directory to save labeled composite images for audit/debugging.",
    )
    parser.add_argument(
        "--dry-run-composite",
        type=Path,
        default=Path("verify_dry_run_example.png"),
        help="Output path for the example composite image generated by --dry-run.",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum retries per verifier request.",
    )
    parser.add_argument(
        "--retry-sleep",
        type=float,
        default=2.0,
        help="Base retry backoff in seconds.",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=512,
        help="Max completion tokens.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.7,
        help="Sampling temperature.",
    )
    parser.add_argument(
        "--top-p",
        type=float,
        default=0.8,
        help="Top-p sampling.",
    )
    parser.add_argument(
        "--presence-penalty",
        type=float,
        default=1.5,
        help="Presence penalty.",
    )
    parser.add_argument(
        "--repetition-penalty",
        type=float,
        default=1.1,
        help="Repetition penalty.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print one example prompt and exit without calling the API.",
    )
    parser.add_argument(
        "--resize-panels",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Resize images when building composite panels. Disable to use original image resolution.",
    )
    return parser.parse_args()


def load_summary_concept_lookup(path: Path) -> dict[int, dict[str, str]]:
    if not path.exists():
        return {}

    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    lookup: dict[int, dict[str, str]] = {}
    for image_record in data.get("images", []):
        image_id = image_record.get("coco_image_id")
        if not isinstance(image_id, int):
            continue

        image_lookup: dict[str, str] = {}
        for key in (
            "concepts_with_mask",
            "concepts_with_bbox",
            "concepts_without_annotation",
        ):
            for concept in image_record.get(key, []):
                if isinstance(concept, str):
                    image_lookup[slugify(concept)] = concept
        lookup[image_id] = image_lookup

    return lookup


def load_processed_pairs(path: Path) -> set[tuple[int, str]]:
    if not path.exists():
        return set()

    processed: set[tuple[int, str]] = set()
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue

            image_id = record.get("coco_image_id")
            concept_slug = record.get("concept_slug")
            if isinstance(image_id, int) and isinstance(concept_slug, str):
                processed.add((image_id, concept_slug))
    return processed


def parse_json_object(text: str) -> dict[str, Any] | None:
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    first = text.find("{")
    last = text.rfind("}")
    if first == -1 or last == -1 or last < first:
        return None

    candidate = text[first : last + 1]
    try:
        parsed = json.loads(candidate)
    except json.JSONDecodeError:
        candidate = candidate.replace(",\n}", "\n}").replace(",}", "}")
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError:
            return None

    return parsed if isinstance(parsed, dict) else None


def normalize_decision(value: Any, valid_labels: set[str]) -> str | None:
    if not isinstance(value, str):
        return None
    decision = value.strip().upper()
    if decision in valid_labels or decision == "REJECT_ALL":
        return decision
    return None


def encode_base64_content(content: bytes) -> str:
    return base64.b64encode(content).decode("utf-8")


def resize_for_panel(image: Image.Image, panel_size: int, resize_panels: bool) -> Image.Image:
    image = image.convert("RGB")
    if not resize_panels:
        return image.copy()
    resized = image.copy()
    resized.thumbnail((panel_size, panel_size), Image.Resampling.LANCZOS)
    return resized


def load_font(size: int) -> ImageFont.ImageFont | ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype("DejaVuSans.ttf", size=size)
    except OSError:
        return ImageFont.load_default()


def measure_text_height(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.ImageFont) -> int:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[3] - bbox[1]


def load_mask_from_tool_dir(tool_dir: Path) -> np.ndarray | None:
    mask_npy = tool_dir / "mask.npy"
    mask_png = tool_dir / "mask.png"

    if mask_npy.exists():
        return np.load(mask_npy)
    if mask_png.exists():
        return np.asarray(Image.open(mask_png).convert("L"), dtype=np.float32) / 255.0
    return None


def make_composite_image(
    original_path: Path,
    candidates: list[tuple[str, str, Path]],
    *,
    panel_size: int = 448,
    label_to_image_gap: int = 10,
    padding: int = 12,
    resize_panels: bool = True,
) -> Image.Image:
    font = load_font(24)
    original_image = Image.open(original_path).convert("RGB")
    panels: list[tuple[str, Image.Image]] = [("Original", original_image)]
    for label, tool_name, tool_dir in candidates:
        mask = load_mask_from_tool_dir(tool_dir)
        if mask is None:
            raise FileNotFoundError(f"No mask found for tool {tool_name} in {tool_dir}")
        overlay = _overlay_mask(
            image=original_image,
            mask=mask,
            image_alpha=1.0,
            contour_width=3,
        )
        panels.append((label, overlay.convert("RGB")))

    resized_panels = [
        (title, resize_for_panel(image, panel_size, resize_panels))
        for title, image in panels
    ]
    columns = min(3, len(resized_panels))
    rows = (len(resized_panels) + columns - 1) // columns

    probe = Image.new("RGB", (1, 1), color="white")
    probe_draw = ImageDraw.Draw(probe)
    label_height = max(
        measure_text_height(probe_draw, title, font)
        for title, _image in resized_panels
    )
    header_height = label_height + label_to_image_gap

    column_widths = [0] * columns
    row_heights = [0] * rows
    for index, (_title, image) in enumerate(resized_panels):
        row = index // columns
        col = index % columns
        column_widths[col] = max(column_widths[col], image.width)
        row_heights[row] = max(row_heights[row], image.height)

    width = sum(column_widths) + (columns + 1) * padding
    height = sum(header_height + row_height for row_height in row_heights) + (rows + 1) * padding
    canvas = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(canvas)

    def x_offset(col: int) -> int:
        return padding + sum(column_widths[:col]) + padding * col

    def y_offset(row: int) -> int:
        return padding + sum(header_height + row_heights[r] for r in range(row)) + padding * row

    for index, (title, image) in enumerate(resized_panels):
        row = index // columns
        col = index % columns
        x = x_offset(col)
        y = y_offset(row)
        draw.text((x + 12, y), title, fill="black", font=font)
        canvas.paste(image, (x, y + header_height))

    return canvas


def composite_to_png_bytes(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


def build_prompt(concept: str, labels: list[str]) -> str:
    label_list = ", ".join(labels)
    choice_list = "\n".join(f"- {label}" for label in labels)
    return f"""You will be given:
1. The original image.
2. A target concept.
3. {len(labels)} candidate annotation proposals, each shown as a visualization over the same image.
   - The proposal is surrounded by bright cyan contour.
   - Each proposal is only a candidate and may be wrong.
   - Candidate panels are labeled: {label_list}

Your task:
Choose exactly one of:
{choice_list}
- REJECT_ALL

Choose the proposal that best grounds the target concept in the image.
If none of the proposals is clearly valid, choose REJECT_ALL.

Important criteria:
1. Concept correctness:
   The selected proposal must correspond to the target concept, not just a visually salient or semantically related region.
   Example: for "red", highlight the red evidence, not the whole object unless the whole object is genuinely the evidence.
   Example: for "left of", the proposal must support the relation, not merely highlight one involved object.

2. Evidence precision:
   Prefer the proposal that marks the most relevant supporting evidence with minimal unnecessary area.
   Do not prefer overly large regions if a smaller region more precisely supports the concept.

3. Evidence sufficiency:
   The selected proposal must include enough visual evidence to justify the concept.
   Reject proposals that are too small, miss critical parts, or omit one side of a relation.

4. Faithfulness over plausibility:
   Do not reward a proposal just because it looks reasonable or because the concept is likely true in the image.
   Judge only whether the highlighted evidence actually supports the target concept.

5. Relation and comparison concepts:
   For relational concepts (such as "on", "behind", "holding", "next to"), the proposal should capture the necessary entities and the relation between them.
   For comparative concepts (such as "bigger", "brighter", "more reflective"), the proposal should include the evidence needed for the comparison.

6. Reject aggressively when needed:
   Choose REJECT_ALL if:
   - all proposals miss the concept,
   - all are too vague or too broad,
   - all are focused on the wrong object or wrong region,
   - the concept is not visually grounded by any proposal,
   - or every option is too weak to support a reasonable choice.

Decision rule:
- Select the label that is the best available grounding when it reasonably supports the concept, even if it is imperfect.
- Choose REJECT_ALL only when none of the candidates provides a reasonable visual grounding.

Output format:
Return a JSON object with exactly these fields:
{{
  "decision": "<one of {label_list}, REJECT_ALL>",
  "confidence": 0.0,
  "reason": "brief explanation"
}}

Requirements for the reason:
- Keep it under 60 words.
- State why the chosen proposal matches or why all should be rejected.
- Mention the key failure mode of the rejected proposals when relevant, such as:
  "too broad", "wrong concept", "misses critical evidence", "object-centric instead of concept-centric", "relation not grounded", or "insufficient visual support".

Prefer the best reasonable match over REJECT_ALL when one candidate is clearly more supportive than the rest.

Target concept: "{concept}".
"""


def collect_candidates(
    concept_dir: Path,
    preferred_tools: list[str],
) -> list[tuple[str, Path]]:
    available: dict[str, Path] = {}
    for tool_dir in sorted(concept_dir.iterdir()):
        if not tool_dir.is_dir():
            continue
        if load_mask_from_tool_dir(tool_dir) is not None:
            available[tool_dir.name] = tool_dir

    ordered_tools = [tool for tool in preferred_tools if tool in available]
    # ordered_tools.extend(tool for tool in sorted(available) if tool not in ordered_tools)
    return [(tool, available[tool]) for tool in ordered_tools]


def call_verifier(
    client: OpenAI,
    *,
    model: str,
    prompt: str,
    image_bytes: bytes,
    max_tokens: int,
    temperature: float,
    top_p: float,
    presence_penalty: float,
    repetition_penalty: float,
    max_retries: int,
    retry_sleep: float,
) -> tuple[str | None, Any]:
    image_base64 = encode_base64_content(image_bytes)

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image_url",
                                "image_url": {"url": f"data:image/png;base64,{image_base64}"},
                            },
                            {"type": "text", "text": prompt},
                        ],
                    },
                ],
                max_completion_tokens=max_tokens,
                temperature=temperature,
                # top_p=top_p,
                # presence_penalty=presence_penalty,
                extra_body={
                    # "top_k": 20,
                    "chat_template_kwargs": {"enable_thinking": False},
                },
            )
            text = response.choices[0].message.content if response.choices else None
            return text, response
        except Exception as exc:
            wait_seconds = retry_sleep * (2 ** attempt)
            log.warning(
                "Verifier request failed on attempt %s/%s: %s",
                attempt + 1,
                max_retries,
                exc,
            )
            if attempt + 1 < max_retries:
                time.sleep(wait_seconds)

    return None, None


def sdk_response_to_dict(response: Any) -> Any:
    if response is None:
        return None
    if hasattr(response, "model_dump"):
        try:
            return response.model_dump()
        except Exception:
            pass
    if hasattr(response, "dict"):
        try:
            return response.dict()
        except Exception:
            pass
    if isinstance(response, (dict, list, str, int, float, bool)) or response is None:
        return response
    return {"repr": repr(response)}


def iter_image_dirs(input_dir: Path, start_image: int, limit_images: int | None) -> list[Path]:
    image_dirs = [path for path in sorted(input_dir.iterdir(), key=lambda p: int(p.name)) if path.is_dir()]
    if start_image < 0:
        raise ValueError("--start-image must be >= 0")
    image_dirs = image_dirs[start_image:]
    if limit_images is not None:
        image_dirs = image_dirs[:limit_images]
    return image_dirs


def format_seconds(total_seconds: float) -> str:
    total_seconds = max(0, int(round(total_seconds)))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours > 0:
        return f"{hours:d}:{minutes:02d}:{seconds:02d}"
    return f"{minutes:d}:{seconds:02d}"


def count_pending_concepts(
    image_dirs: list[Path],
    processed_pairs: set[tuple[int, str]],
    limit_concepts: int | None,
) -> int:
    total = 0
    for image_dir in image_dirs:
        concept_dirs = [path for path in sorted(image_dir.iterdir()) if path.is_dir()]
        if limit_concepts is not None:
            concept_dirs = concept_dirs[:limit_concepts]
        for concept_dir in concept_dirs:
            pair = (int(image_dir.name), concept_dir.name)
            if pair not in processed_pairs:
                total += 1
    return total


def main() -> None:
    args = parse_args()

    if not args.api_key and not args.dry_run:
        raise ValueError("API key is required. Set OPENAI_API_KEY or pass --api-key.")
    if not args.input_dir.exists():
        raise FileNotFoundError(f"Input directory not found: {args.input_dir}")

    if args.overwrite and args.output_jsonl.exists():
        args.output_jsonl.unlink()

    processed_pairs = set() if args.overwrite else load_processed_pairs(args.output_jsonl)
    concept_lookup = load_summary_concept_lookup(args.summary_json)
    image_dirs = iter_image_dirs(args.input_dir, args.start_image, args.limit_images)

    if args.dry_run:
        if not image_dirs:
            print("No image directories found.")
            return
        example_image_dir = image_dirs[0]
        concept_dirs = [path for path in sorted(example_image_dir.iterdir()) if path.is_dir()]
        if not concept_dirs:
            print(f"No concept directories found in {example_image_dir}")
            return
        candidates = collect_candidates(concept_dirs[0], list(args.tools))
        print(candidates)
        labels = list(string.ascii_uppercase[: len(candidates)])
        concept = concept_lookup.get(int(example_image_dir.name), {}).get(concept_dirs[0].name, concept_dirs[0].name)
        labeled_candidates = [
            (label, tool_name, tool_dir)
            for label, (tool_name, tool_dir) in zip(labels, candidates)
        ]
        composite = make_composite_image(
            example_image_dir / "original.png",
            labeled_candidates,
            resize_panels=args.resize_panels,
        )
        args.dry_run_composite.parent.mkdir(parents=True, exist_ok=True)
        composite.save(args.dry_run_composite)
        print(f"Saved example composite image to: {args.dry_run_composite}")
        print()
        print(build_prompt(concept, labels))
        return

    client_kwargs: dict[str, Any] = {"api_key": args.api_key}
    if args.base_url:
        client_kwargs["base_url"] = args.base_url
    client = OpenAI(**client_kwargs)

    args.output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    if args.save_composites_dir is not None:
        args.save_composites_dir.mkdir(parents=True, exist_ok=True)

    total_pending = count_pending_concepts(image_dirs, processed_pairs, args.limit_concepts)
    completed = 0
    started_at = time.time()
    log.info("Pending concepts to verify: %s", total_pending)

    with args.output_jsonl.open("a", encoding="utf-8") as out_handle:
        for image_dir in image_dirs:
            image_id = int(image_dir.name)
            original_path = image_dir / "original.png"
            if not original_path.exists():
                log.warning("Skipping image %s: missing original.png", image_id)
                continue

            concept_dirs = [path for path in sorted(image_dir.iterdir()) if path.is_dir()]
            if args.limit_concepts is not None:
                concept_dirs = concept_dirs[: args.limit_concepts]

            for concept_dir in concept_dirs:
                concept_slug = concept_dir.name
                if (image_id, concept_slug) in processed_pairs:
                    continue

                candidates = collect_candidates(concept_dir, list(args.tools))
                record: dict[str, Any] = {
                    "coco_image_id": image_id,
                    "concept_slug": concept_slug,
                    "concept": concept_lookup.get(image_id, {}).get(concept_slug, concept_slug),
                    "model": args.model,
                    "candidate_tools": [tool for tool, _ in candidates],
                    "decision": None,
                    "selected_tool": None,
                    "confidence": None,
                    "reason": None,
                    "raw_text": None,
                    "raw_response": None,
                    "error": None,
                }

                if len(candidates) < args.min_candidates:
                    record["error"] = f"insufficient_candidates:{len(candidates)}"
                    out_handle.write(json.dumps(record, ensure_ascii=False) + "\n")
                    out_handle.flush()
                    processed_pairs.add((image_id, concept_slug))
                    continue

                labels = list(string.ascii_uppercase[: len(candidates)])
                labeled_candidates = [
                    (label, tool_name, tool_dir)
                    for label, (tool_name, tool_dir) in zip(labels, candidates)
                ]

                composite = make_composite_image(
                    original_path,
                    labeled_candidates,
                    resize_panels=args.resize_panels,
                )
                if args.save_composites_dir is not None:
                    composite_path = args.save_composites_dir / str(image_id) / f"{concept_slug}.png"
                    composite_path.parent.mkdir(parents=True, exist_ok=True)
                    composite.save(composite_path)

                prompt = build_prompt(record["concept"], labels)
                image_bytes = composite_to_png_bytes(composite)

                log.info(
                    "Verifying image %s concept %s with %s candidates",
                    image_id,
                    concept_slug,
                    len(candidates),
                )
                raw_text, raw_response = call_verifier(
                    client,
                    model=args.model,
                    prompt=prompt,
                    image_bytes=image_bytes,
                    max_tokens=args.max_tokens,
                    temperature=args.temperature,
                    top_p=args.top_p,
                    presence_penalty=args.presence_penalty,
                    repetition_penalty=args.repetition_penalty,
                    max_retries=args.max_retries,
                    retry_sleep=args.retry_sleep,
                )

                record["raw_text"] = raw_text
                record["raw_response"] = sdk_response_to_dict(raw_response)

                if raw_text is None:
                    record["error"] = "request_failed"
                else:
                    parsed = parse_json_object(raw_text)
                    if parsed is None:
                        record["error"] = "json_parse_failed"
                    else:
                        valid_labels = set(labels)
                        decision = normalize_decision(parsed.get("decision"), valid_labels)
                        if decision is None:
                            record["error"] = "invalid_decision"
                        else:
                            record["decision"] = decision
                            record["confidence"] = parsed.get("confidence")
                            record["reason"] = parsed.get("reason")
                            if decision != "REJECT_ALL":
                                label_to_tool = {label: tool for label, tool, _tool_dir in labeled_candidates}
                                record["selected_tool"] = label_to_tool[decision]

                out_handle.write(json.dumps(record, ensure_ascii=False) + "\n")
                out_handle.flush()
                processed_pairs.add((image_id, concept_slug))
                completed += 1
                elapsed = time.time() - started_at
                avg_seconds = elapsed / completed if completed else 0.0
                remaining = max(total_pending - completed, 0)
                eta_seconds = remaining * avg_seconds
                log.info(
                    "Progress %s/%s, elapsed=%s, eta=%s",
                    completed,
                    total_pending,
                    format_seconds(elapsed),
                    format_seconds(eta_seconds),
                )


if __name__ == "__main__":
    main()
